---
# tasks file for sos-report
# - name: debugging
#   debug:
#     var: ansible_facts

- name: Install sos-report | Fedora
  yum:
    name: sos
    state: latest
    update_cache: yes
  when: 
    - ansible_facts['distribution'] == "Fedora"
    - ansible_facts['distribution_major_version'] >= "34"


- name: Install sos-report | CentOS
  yum:
    name: sos
    state: latest
    update_cache: yes
  when: 
    - ansible_facts['distribution'] == "CentOS"
    - ansible_facts['distribution_major_version'] >= "7"

- name: Install sos-report | RedHat
  yum:
    name: sos
    state: latest
    update_cache: yes
  when: 
    - ansible_facts['distribution'] == "RedHat"
    - ansible_facts['distribution_major_version'] >= "7"

- name: Install sos-report | Ubuntu
  apt:
    name: sosreport
    state: latest
    update_cache: yes
  when: 
    - ansible_facts['distribution'] == "Ubuntu"
    - ansible_facts['distribution_major_version'] >= "16"

- name: Install sos-report | Debian 9
  apt:
    name: sosreport
    state: latest
    update_cache: yes
  when: 
    - ansible_facts['distribution'] == "Debian"
    - ansible_facts['distribution_major_version'] >= "9"
