---
- name: Start sos-report | CentOS
  command: >
    sosreport 
    --o "{{ sos_modules }}" 
    --name "{{ costumer }}" 
    --case-id "{{ ticket_number }}" 
    --tmp-dir "{{ tmp_dir }}" 
    -z gzip
    --batch
  when: 
    - ansible_facts['distribution'] == "CentOS"
    - ansible_facts['distribution_major_version'] == "7"
  
- name: Start sos-report | Ubuntu
  command: >
    sosreport 
    --o "{{ sos_modules|join(',') }}" 
    --name "{{ costumer }}" 
    --case-id "{{ ticket_number }}" 
    --tmp-dir "{{ tmp_dir }}" 
    -z gzip
    --batch
  when: 
    - ansible_facts['distribution'] == "Ubuntu"
    - ansible_facts['distribution_major_version'] >= "16"

- name: Start sos-report | RedHat
  command: >
    sosreport 
    --o "{{ sos_modules|join(',') }}" 
    --name "{{ costumer }}" 
    --case-id "{{ ticket_number }}" 
    --tmp-dir "{{ tmp_dir }}" 
    -z gzip
    --batch
  when: 
    - ansible_facts['distribution'] == "RedHat"
    - ansible_facts['distribution_major_version'] >= "7"

- name: Start sos-report | Debian 9
  command: >
    sosreport 
    --o "{{ sos_modules|join(',') }}" 
    --name "{{ costumer }}" 
    --case-id "{{ ticket_number }}" 
    --tmp-dir "{{ tmp_dir }}" 
    -z gzip
    --batch
  when: 
    - ansible_facts['distribution'] == "Debian"
    - ansible_facts['distribution_major_version'] >= "9"

- name: Start sos-report | Generic
  command: >
    sos report 
    --o "{{ sos_modules|join(',') }}" 
    --name "{{ costumer }}" 
    --case-id "{{ ticket_number }}" 
    --tmp-dir "{{ tmp_dir }}" 
    -z gzip
    --batch
  when: >
    (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] != "16")  or
    (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] != "7")  or
    (ansible_facts['distribution'] == "Debian" and ansible_facts['distribution_major_version'] != "9") or
    (ansible_facts['distribution'] == "Fedora" and ansible_facts['distribution_major_version'] == "34")

# Fetching report file
- name: Search report file from remote
  find:
    path: "{{ tmp_dir }}"
    patterns: "*{{ costumer }}[-|.]{{ ticket_number }}*.tar.gz"
  register: reportFile

# - name: Debugging
#   debug:
#     var: reportFile

- name: Fetch the remote file to local
  fetch:
    src: "{{ reportFile['files'][0]['path'] }}"
    dest: "{{ fetch_to }}"
    flat: yes
  when:
    - reportFile | length > 0