--- # Getting sys report with sos
- hosts: work
  become: yes
  vars:
    tmp_dir: /tmp/
    fetch_to: /tmp/
    ticket_number: 0001
    costumer: 'test'
    sos_modules: npm
  tasks:
    # - name: debugging
    #   debug:
    #     var: ansible_facts
    - name: Install dependencies | Centos7
      yum:
        name: epel-release
        state: latest
      when:
        - ansible_distribution == "CentOS"
        - ansible_distribution_major_version == "7"

    - name: Install sos-report | Fedora
      yum:
        name: sos
        state: latest
        update_cache: yes
      when: 
        - distribution == "Fedora"
        - distribution_major_version >= "34"

    - name: Install sos-report | CentOS
      yum:
        name: sos
        state: latest
        update_cache: yes
      when: 
        - ansible_distribution == "CentOS"
        - ansible_distribution_major_version >= "7"

    - name: Install sos-report | RedHat
      yum:
        name: sos
        state: latest
        update_cache: yes
      when: 
        - distribution == "RedHat"
        - distribution_major_version >= "7"

    - name: Install sos-report | Ubuntu
      apt:
        name: sosreport
        state: latest
        update_cache: yes
      when: 
        - ansible_distribution == "Ubuntu"
        - distribution_major_version >= "16"

    - name: Install sos-report | Debian 9
      apt:
        name: sosreport
        state: latest
        update_cache: yes
      when: 
        - distribution == "Debian"
        - distribution_major_version >= "9"
    
    ## TODO :: Specify sos-report run command
    - name: Start sos-report | CentOS
      command: >
        sosreport 
        --o "{{ sos_modules }}" 
        --name "{{ costumer }}" 
        --case-id "{{ ticket_number }}" 
        --tmp-dir "{{ tmp_dir }}" 
        -z gzip
        --batch
      when: 
        - ansible_distribution == "CentOS"
        - ansible_distribution_major_version == "7"
      
    - name: Start sos-report | Ubuntu16
      command: >
        sosreport 
        --o "{{ sos_modules }}" 
        --name "{{ costumer }}" 
        --case-id "{{ ticket_number }}" 
        --tmp-dir "{{ tmp_dir }}" 
        -z gzip
        --batch
      when: 
        - ansible_distribution == "Ubuntu"
        - distribution_major_version >= "16"

    - name: Start sos-report | RedHat7
      command: >
        sosreport 
        --o "{{ sos_modules }}" 
        --name "{{ costumer }}" 
        --case-id "{{ ticket_number }}" 
        --tmp-dir "{{ tmp_dir }}" 
        -z gzip
        --batch
      when: 
        - distribution == "RedHat"
        - distribution_major_version >= "7"

    - name: Start sos-report | Debian9
      command: >
        sosreport 
        --o "{{ sos_modules }}" 
        --name "{{ costumer }}" 
        --case-id "{{ ticket_number }}" 
        --tmp-dir "{{ tmp_dir }}" 
        -z gzip
        --batch
      when: 
        - distribution == "Debian"
        - distribution_major_version >= "9"

    - name: Start sos-report | Generic
      command: >
        sos report 
        --o "{{ sos_modules }}" 
        --name "{{ costumer }}" 
        --case-id "{{ ticket_number }}" 
        --tmp-dir "{{ tmp_dir }}" 
        -z gzip
        --batch
      when:
        - ansible_distribution != "Ubuntu"
        - distribution_major_version != "16"
        - ansible_distribution != "CentOS"
        - ansible_distribution_major_version != "7"
        - distribution != "RedHat"
        - distribution_major_version != "7"
        - distribution != "Debian"
        - distribution_major_version != "9"

    # Fetching report file
    - name: Search report file from remote
      find:
        path: "{{ tmp_dir }}"
        patterns: "*{{ costumer }}[-|.]{{ ticket_number }}*.tar.gz"
      register: reportFile
    
    # - name: Debugging
    #   debug:
    #     var: reportFile

    - name: Fetch the remote file to local
      fetch:
        src: "{{ reportFile['files'][0]['path'] }}"
        dest: "{{ fetch_to }}"
        flat: yes
      when:
        - reportFile | length > 0
      

    
        